image: docker:latest
stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: nodeanddocker:latest

build:
  stage: build
  script:
    - sudo service docker restart
    - docker build -t $DOCKER_IMAGE .

test:
  stage: test
  script:
    - docker run $DOCKER_IMAGE npm test

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE
  only:
    - main
